apiVersion: v1
kind: ConfigMap
metadata:
  name: jobboards-logstash-pipeline
  labels:
    app: jobboards-logstash
data:
  input.yaml: |-
    input {
      google_pubsub {
        project_id => "toixotoixo"
        topic => "jobboards"
        subscription => "jobboards-logstash"
        json_key_file => "/usr/share/keys/key.json"
        create_subscription => false
      }
    }

  filter.yaml: |-
    filter {
      json {
        source => "message"
      }
    }

  output.yaml: |-
    output {
      s3 {
        access_key_id => "${AWS_ACCESS_KEY_ID}"
        secret_access_key => "${AWS_SECRET_ACCESS_KEY}"
        region => "eu-west-1"
        bucket => "oecd-scraping"
        prefix => "v2/indeed-%{[country]}/%{+YYYY}-%{+MM}-%{+DD}"
        size_file => 128000000
        time_file => 20
        upload_queue_size => 256
        upload_workers_count => 2
        codec => line { format => "%{message}" }
        canned_acl => "private"
      }
      google_cloud_storage {
        bucket => "indeed-scrapes"
        codec => line { format => "%{message}" }
        output_format => "json"
        flush_interval_secs => 2
        gzip_content_encoding => true
        include_hostname => false
        key_path => "/usr/share/keys/key.p12"
        key_password => "notasecret"
        max_file_size_kbytes => 128000
        service_account => "jobboards-logstash@toixotoixo.iam.gserviceaccount.com"
        uploader_interval_secs => 1200
      }
    }
